### ISSUE TITLE
Merge environment on update

### ISSUE THREAD

**Issue by albinekb** [LinusU/scandium#14]
Currently when you do `scandium update --env A=b` it will overwrite all the currently set env vars, I don't think this is expected since `update` without any env vars will keep the currently set ones.

Is it possible to read the env, merge it? Thoughts?

**Comment by LinusU** [comment]
Yeah, that seems like the expected behavior 👍 

We'll probably need to do a read, local merge, and the put; but that should be okay

PR Welcome!
