### ISSUE TITLE
Calling the Invoke API failed with message: Lambda was not able to unzip the file

### ISSUE THREAD

**Issue by albinekb** [LinusU/scandium#21]
![image](https://user-images.githubusercontent.com/5027156/36541042-e77ca2fc-17dc-11e8-871b-749ea9a63b82.png)

I have no idea what's causing this. From CircleCI It's working, but when I build locally I get this error.

**Comment by LinusU** [comment]
Hmm 🤔 

Maybe it could be a macOS problem? It adding extra strange files to the zip?

**Comment by albinekb** [comment]
Don't know, not seen this again. I will reopen if it happens 👍
