### ISSUE TITLE
The role defined for the function cannot be assumed by Lambda

### ISSUE THREAD

**Issue by androidand** [LinusU/scandium#31]
Hej. I'm hitting the following issue on my maiden voyage with Scandium. Also, re-attempting this fails because the role is already created (so I manually deleted the role and tried again but same error).

scandium create --name=somename
 ✔ Parse options
 ✔ App packaged successfully! Final size: 18.55MB
 ✔ Created new Lambda role with ARN: arn:aws:iam::somenumber:role/somename
 ✖ Creating Lambda function
   **→ The role defined for the function cannot be assumed by Lambda.**
   Generate Swagger definition
   Creating new API Gateway
   Deploying the API to a live address
InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.
    at Object.extractError (/Users/myname/.nvm/versions/node/v9.3.0/lib/node_modules/scandium/node_modules/aws-sdk/lib/protocol/json.js:48:27)

Ideas?

**Comment by androidand** [comment]
I think this is some issue with AWS. I tried again with a different (shorter) name and it works.

**Comment by LinusU** [comment]
Hmm, I think that this is something that both me and @albinekb have run into. Basically the role just isn't ready at that time.

I think a good fix is adding a retry, for specific error codes, to the "create Lambda" step.

I'd be happy to help you debug the next.js problem as well ☺️

**Comment by albinekb** [comment]
PR up for retrying to create the function (to wait for the role to be available) 👍 #32

**Comment by LinusU** [comment]
Released as `v1.0.0-alpha.30` 🚀
