### ISSUE TITLE
Deployment without API Gateway

### ISSUE THREAD

**Issue by albinekb** [LinusU/scandium#33]
What do you think of adding an option like `--lambda-only`, and skip the steps here: https://github.com/LinusU/scandium/blob/master/app.js#L62-L65

To make scandium able to deploy regular plain Lambda functions?

**Comment by LinusU** [comment]
How would you like it to work with the entrypoint?

**Comment by albinekb** [comment]
Using my own entrypoint 👍

**Comment by albinekb** [comment]
Done https://github.com/LinusU/scandium/pull/55 🎉
