### ISSUE TITLE
error on run the create command

### ISSUE THREAD

**Issue by raisiqueira** [LinusU/scandium#38]
I fallowed this tutorial, but on the time to run the `scandium` command return this error:

![captura de tela 2018-06-14 as 09 02 51](https://user-images.githubusercontent.com/2914170/41411118-11462e3c-6fb2-11e8-863e-dba81bb315bd.png)

**Comment by LinusU** [comment]
Seems like you don't have docker installed. We should probably document this better, but currently, you have to install docker first in order to use scandium.

Here are some docs to get you started: https://docs.docker.com/install/
