### ISSUE TITLE
Convert to TS?

### ISSUE THREAD

**Issue by albinekb** [LinusU/scandium#44]
I can provide a PR 😄 Do you know if ts-node hook does caching of the built files? It  would only be nice with TS if we could have "seamless start", so you don't need to remember to start the compiler?

**Comment by LinusU** [comment]
I believe that we discussed this a bit offline when you opened this, but just to quickly get down some of my thoughts:

- Not having a transpile step means that you can depend on specific commit directly from Github
- VS Code gives us much of the validation as it is, especially when properly using JSDoc

That said, I'm not totally against this but I think that it's quite clean as it is now 🤔

**Comment by albinekb** [comment]
Yes not needed 😄 I closed this as it's so nice to be able to test scandium by just running app.js
