### ISSUE TITLE
Add alias for prepare script

### ISSUE THREAD

**Issue by albinekb** [LinusU/scandium#48]
I have `"prepare": "next build",` in my package.json, but when using `yarn`, this runs *every time i add/remove a package*, even on dependency install it runs the build right after, even though it's not necessary in dev.

What about adding `scandium:prepare` as a second key?

**Comment by albinekb** [comment]
Workaround for now `"prepare": "ps -p1 | grep 'init' -q -R && next build || echo 'Skipping prepare'",` 😄

**Comment by LinusU** [comment]
another workaround: `yarn --ignore-scripts`

**Comment by albinekb** [comment]
you mean I should tell everyone to use `yarn --ignore-scripts` when they work in projects using scandium? 😄

**Comment by albinekb** [comment]
can't we make it run `build` if there's no "prepare"?

**Comment by LinusU** [comment]
> you mean I should tell everyone to use yarn --ignore-scripts when they work in projects using scandium? 😄

Well, `prepare` has nothing to do with Scandium, it's the npm defined script for preparing the package...

Hmm, actually, I think that the `prepare` script isn't supposed to run when adding or removing, only when running `npm install` without any arguments.

I'm open to adding something else as well, but it feels like this is a specific problem that only happens with yarn?

Another thing; we might actually be running the `prepare` script twice during the build step as it is now 😱 We should probably double check that...

**Comment by albinekb** [comment]
Yes, I think it runs twice since my build in scandium takes about twice as long 😄

**Comment by albinekb** [comment]
In now.sh they run `build`, isn't that "standard"?

**Comment by LinusU** [comment]
If now.sh uses `build` I'm happy with us picking up that as well 👍

**Comment by LinusU** [comment]
Fixed by 443ad8f1c94d27237758dd4e49223670ffba2ed0
