### ISSUE TITLE
max buffer exceeded 

### ISSUE THREAD

**Issue by sc4224** [LinusU/scandium#49]
<img width="499" alt="screen shot 2018-11-29 at 2 53 30 am" src="https://user-images.githubusercontent.com/30026659/49207111-0893c480-f382-11e8-8dc4-79da69171b6c.png">

**Comment by LinusU** [comment]
We should probably make this error more clear, but it seems like you are running into this (https://github.com/LinusU/scandium/blob/c218ea77efd9b193214c6a674b9eee2606181aec/lib/builder.js#L70) limitation.

Unfortunately, Lambda has a maximum zip size of 50MB, or 100MB if you upload via S3.

Do you know why the built app is so large? Some things you can try are:

- making sure only dependencies needed to run the app are in `dependencies`, and anything else in `devDependencies`
- make sure that files not needed are properly ignored by a `.gitignore` or `.dockerignore`

**Comment by LinusU** [comment]
Actually, a problem with the code capped at 75MB instead of 100MB, this should be fixed in `1.0.0-alpha.40`, see #51

**Comment by LinusU** [comment]
ping @sc4224 ☺️ any updates? did you try the tricks I mentioned, or the newer version?

**Comment by LinusU** [comment]
closing since it should be fixed in alpha.40...
