### ISSUE TITLE
Look for a way to improve CircleCI output

### ISSUE THREAD

**Issue by albinekb** [LinusU/scandium#7]
Just using https://github.com/SamVerschueren/listr doesn't seem to be enough 🤔 

![kapture 2018-02-09 at 11 46 00](https://user-images.githubusercontent.com/5027156/36024062-d733ae48-0d8e-11e8-8b48-cb77b11cb59f.gif)

**Comment by albinekb** [comment]
https://github.com/SamVerschueren/listr-verbose-renderer

**Comment by LinusU** [comment]
😞 

> https://github.com/SamVerschueren/listr-verbose-renderer

Looks very nice! I think we should try and submit a PR to listr that uses it by default if CI is detected?

**Comment by LinusU** [comment]
https://yarnpkg.com/en/package/is-ci
